### ISSUE TITLE
建議將「香港字型標準」改為「香港教育字形參考」

### ISSUE THREAD

**Issue by aikahiiragi** [ItMarki/jyunsaikaai#1]
正如《常用字字形表》編者所說，《字形表》是一份以小學語文教師為主要對象的語文教學參考資料，目的在減少小學語文教師因異體字太多而產生的困擾。但《字形表》的編訂者表示，他們無意樹立「正字」權威。學生習作上的字，雖或與表中所列的教育參考字形未盡相符，只要是通行的異體字而不是錯別字，教師宜採取較寬容態度。《字形表》的編訂者在序言、說明中多番表明無意樹立「正字」權威。並且表明《字形表》字形僅適用於手寫楷書，以及教科書裏的楷書示範字形。換言之，即使在教學用途，《常用字字形表》也只是一套參考，而不是必定要依從、不依從就是錯誤了的標準。更何況在教育用途以外，香港日常的出版印刷及其他場合的用字，基於不同的場合、需求或原因，並未以《字形表》一鎚定音。如果說成是「香港字形標準」，就好像有想約束其他場合的意味了。因此提出這個小小的建議，耽耗了大大的聆聽時間，非常感謝！

**Comment by ItMarki** [comment]
已於v0.3.0修改。
