### ISSUE TITLE
肅 蕭 瀟 嘯 繡 鏽 ....等字不符合港標

### ISSUE THREAD

**Issue by jisbig5** [ItMarki/jyunsaikaai#2]
肅 蕭 瀟 嘯 繡 鏽 等字與台標最大的不同 是多一個橫
這個橫 比台標更符合字源 建議修正
比如 及 吸 户等 這些沒有台標正 改不改無所謂的

**Comment by ItMarki** [comment]
「肅」的問題已於v0.3.0修改。
