### ISSUE TITLE
字重

### ISSUE THREAD

**Issue by raxzak** [ItMarki/jyunsaikaai#3]
某些light字重和bold字重反轉了，如pdf內的「體」、「化」、「少」、「廣」、「沙」、「妙」等。

[jyunsaikaai.pdf](https://github.com/ItMarki/jyunsaikaai/files/11108555/jyunsaikaai.pdf)

**Comment by ItMarki** [comment]
我用FontCreator調整字形時，一些字形會反向加粗/減細（即是我加粗字形，它就會減細，反之亦然）。我不知道其中原因是甚麼，所以請耐心等待。

**Comment by ItMarki** [comment]
問題已修正。
