### ISSUE TITLE
中文符号位置很显眼

### ISSUE THREAD

**Issue by lion-no-back** [ItMarki/jyunsaikaai#5]
作者大大，你好，感谢你开源了这款字体

问题：用了一段时间，感觉很不错，但今天发现了一个问题，就是中文符号位置不同以往字体的位置，看起来很不得劲儿，请问这是特色设置嘛，有没有常规设置

![image](https://github.com/ItMarki/jyunsaikaai/assets/100990301/07d4aef4-8ca4-44ef-9bd8-ef38c733a39b)

再次感谢开源了这款字体

**Comment by ItMarki** [comment]
在香港标准下，标点符号的位置一般是置中的，和台湾的一样。这些标点符号的字形是沿用芫荽的。
